title: Sinister_final
description: Ejercicio de LMSXI.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">                 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sinister</title>
    <style> table, tr, td {
        border: 1px solid black;
        border-collapse: collapse;
        text-align: center;
    }
    </style>


    <nav><ul>
        <li><a href="#" title="Inicio">Inicio</a></li>
        <li><a href="#" title="Director">Director</a></li>
        <li><a href="#" title="Personajes">Personajes</a></li>
        <li><a href="#" title="Streaming">Streaming</a></li>
        <li><a href="#" title="Media">Media</a></li>
        <li><a href="#" title="Opinión">Opinión</a></li>
        <li><a href="#" title="Links">Links</a></li>
        <li><a href="#" title="Otra Información">Otra Información</a></li>
    </ul></nav>
</head>
<header>
    <h1>Sinister</h1>
    <img src="images/cartel.jpg">
</header>
<body>
    <form>

            <h2>Inicio</h2>
            <b>Argumento: </b>
            <p>
                Un novelista de crímenes reales viaja con su familia a lo largo del país para investigar terribles asesinatos que luego convierte en libros. Cuando llega a una casa donde ha tenido lugar el asesinato de una familia, encuentra una cinta que desvela horribles pistas que van más allá del esclarecimiento de la tragedia. 
            </p>
            <b>Datos generales: </b>
            <ul>
                <li><b>Título:</b><p> Sinister</p></li>
                <li><b>Fecha de estreno:</b><p> 11 de marzo de 2012</p></li>
                <li><b>Género:</b><p> Terror, sobrenatural</p></li>
                <li> <b>Clasificación por edades:</b><p>No recomendada para menores de 16 años.</p></li>
                <li><b>Reparto:</b><p>Ethan Hawke, James Ransone, Juliet Rylance</p></li>
                <li><b>Premios:</b></li>
                <ul>
                    <li>Festival de Cine SXWS  (2012)</li>
                    <li>Festival de Cine Internacional de Estocolmo (2012)</li>
                    <li>Fright Meter Awards (2012)</li>
                </ul>
            </ul>

            <h2>Director</h2>
            <ul>
                <li><b>Nombre:</b><p>Scott Derrickson</p></li>
                <li><b>Nacionalidad:</b><p>Estadounidense</p></li>
                <li><b>Profesión: </b><p>Director de cine, guionista y productor</p></li>
                <li><b>Educación:</b><p>Universidad de Biola, Escuela de Artes Cinematrográficas del Sur de California</p></li>
                <li><b>Películas:</b><p>The Black Phone, Doctor Strange, El exorcismo de Emily Rose</p></li>
            </ul>
            
            <h2>Personajes</h2>
                <div><b>Ellison Oswalt</b><br>
                    <p>Novelista de crímenes que intenta conseguir escribir un libro de éxito, como el que le lanzó a la fama 10 años atrás.</p>
                    <img src="images/ellison.jpg"
                    width="170"
                    height="110">
                </div>
                <div><b>Tracy Oswalt</b><br>
                    <p>Esposa de Ellison y madre de los niños. Desconfía del éxito que le asegura su marido y quiere todo lo relacionado con los asesinatos lejos de ella y sus hijos.</p>
                    <img src="images/tracy.jpg"
                    width="150">
                </div>
                <div><b>Oficial "So & So"</b><br>
                    <p>Agente de policía que es fan de Ellison y lo ayudará en su investigación.</p>
                    <img src="images/james.jpg"
                    widht="190"
                    height="170">
                </div>
                <div><b>Ashley Oswalt</b><br>
                    <p>Hija pequeña del matrimonio y aficionada al arte. Será la más sensible a los acontecimientos sobrenaturales que ocurren en la casa.</p>
                    <img src="images/ashley.jpg"
                    width="250"
                    height="150">
                </div>
                <div><b>Trevor Oswalt</b><br>
                    <p>Hijo mayor, un chico reservado que sufre de terrores nocturnos y sonambulismo desde muy pequeño.</p>
                    <img src="images/trevor.jpg"
                    width="150">
                </div>
            
        
            <h2>Streaming</h2>
            <table>
                <tr>
                    <td colspan="5">Plataformas en las que está disponible</td>
                </tr>
                <tr>
                    <td rowspan="3">Plataformas<br>Precio<br>Valoración</td>
                    <td><a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi89vqKkMX0AhUE5uAKHY75Cd0QFnoECAQQAQ&url=https%3A%2F%2Fwww.netflix.com%2Fes%2Ftitle%2F70221486&usg=AOvVaw3iD5mh85emuODBxiIg1WLr">Netflix</a></td>
                    <td><a href="https://www.filmin.es/pelicula/sinister?utm_source=justwatch">Filmin</a></td>
                    <td><a href="https://ver.movistarplus.es/ficha/sinister?id=1082842">Movistar Plus</a></td>
                    <td><a href="https://play.google.com/store/movies/details/Sinister?gl=ES&hl=en&id=Ut6oc_NUaRk">Google Plar Movies</a></td>
                </tr>
                <tr>
                    
                    <td>Incluida con la subscripción</td>
                    <td>Incluida con la subscripción</td>
                    <td>Incluida con la subscripción</td>
                    <td>3,99€</td>
                </tr>
                <tr>
                    
                    <td>3,6/5</td>
                    <td>5,9/10</td>
                    <td>4,3/5</td>
                    <td>3/5</td>
                </tr>
            </table>

            <h2>Media</h2>
            <h3>Galería de imágenes</h3>
            <img src="images/1.jpg"
                    width="150"
                    height="150">
            <img src="images/2.webp"
                    width="250"
                    height="150">
            <img src="images/3.jpg"
                    width="200"
                    height="150">
            <img src="images/4.jpg"
                    width="200"
                    height="150">
            <img src="images/5.jpg"
                    width="200"
                    height="150">
            <img src="images/6.jpg"
                    width="200"
                    height="150">

        <h3>Tráiler</h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/pUklYZdiycQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <h3>Vídeo personal de recomendación</h3>
        <video src="Sinister_Video.mp4" width="560" height="315" controls poster=""></video>

            <h2>Opinión</h2>
            <form>
                <ol>
                    <li>
                        <label for="name">Nombre: </label>
                        <input type="text" id="name" name="nombre">
                    </li>
                    
                <li>
                    <label for="email">Correo electrónico: </label>
                    <input type="email" id="email" name="correo">
                </li>
                
                <li>
                    <label for="p1">Del 1 al 10, ¿de cuanto crees que es la película? </label>
                    <input type="number" id="p1" name="pregunta1">
                </li>
                <li>
                    <label for="p2">De las cintas de video que aparecen, ¿cuál es tu favortita? </label>
                    <input type="text" id="p2" name="pregunta2">
                </li> 
                <li>
                    <label for="p3">¿A través de que plataforma la viste? </label>
                    <input type="text" id="p3" name="pregunta3">
                </li>
                <li>
                    <label for="p4">¿La recomedarías a alguien?¿Por qué?</label>
                    <textarea id="p4" name="pregunta4"></textarea>
                </li>
                </ol>
                

            </form>

        <h2>Links</h2>
            <ul>
                <li><a href="https://www.filmaffinity.com/es/film262844.html">FilmAffinity</a></li>
                <li><a href="https://www.sensacine.com/peliculas/pelicula-200962/">SensaCine</a></li>
                <li><a href="https://www.imdb.com/title/tt1922777/">IMDb</a></li>
                <li><a href="https://es.wikipedia.org/wiki/Sinister">Wikipedia</a></li>
                <li><a href="https://decine21.com/peliculas/sinister-24797">Decine21</a></li>
            </ul>


        <h2>Otra Información</h2>  
        <ul>
            <li>Hay una secuela "Sinister 2" que transcurre unos años después de la primera y también tiene a James Ransone en su reparto.</li>
            <li>Se inspiró en una pesadilla que el coguionista C. Robert Cargill tuvo después de ver la película de 2002 The Ring.</li>
            <li>Recibió críticas positivas, elogiando la actuación, la dirección, la música, la cinematografía y la atmósfera, pero también críticas por su uso de sustos de salto (especialmente la escena de la cortadora de césped) y otros clichés de terror.</li>
            <li>La película fue un éxito de taquilla, recaudando $ 87.7 millones contra su presupuesto de $ 3 millones.</li>
            <li>Bagul,también conocido como Buhguul y Mr. Boogie,es el principal antagonista. Es una antigua deidad pagana babilónica que consume las almas de los niños humanos. Posee un reino propio y puede viajar al mundo mortal a través de imágenes de sí mismo.</li>
        </ul>  
        </body>
    </html>